/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateOrgRouteImport } from './routes/create-org'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSystemTemplatesIndexRouteImport } from './routes/admin/system-templates/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminServerIndexRouteImport } from './routes/admin/server/index'
import { Route as AdminPlansIndexRouteImport } from './routes/admin/plans/index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminFeatureFlagsIndexRouteImport } from './routes/admin/feature-flags/index'
import { Route as AdminEimsIndexRouteImport } from './routes/admin/eims/index'
import { Route as AdminBillingIndexRouteImport } from './routes/admin/billing/index'
import { Route as AdminAuditLogsIndexRouteImport } from './routes/admin/audit-logs/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedFilesIndexRouteImport } from './routes/_authenticated/files/index'
import { Route as AuthenticatedEimsIndexRouteImport } from './routes/_authenticated/eims/index'
import { Route as AdminPlansNewRouteImport } from './routes/admin/plans/new'
import { Route as AdminPlansPlanIdRouteImport } from './routes/admin/plans/$planId'
import { Route as AdminOrganizationsOrgIdRouteImport } from './routes/admin/organizations/$orgId'
import { Route as AdminEimsTenantsRouteImport } from './routes/admin/eims/tenants'
import { Route as AdminEimsResourcesRouteImport } from './routes/admin/eims/resources'
import { Route as AdminEimsFailuresRouteImport } from './routes/admin/eims/failures'
import { Route as AdminEimsComplianceRouteImport } from './routes/admin/eims/compliance'
import { Route as AdminEimsCertificatesRouteImport } from './routes/admin/eims/certificates'
import { Route as AdminBillingDashboardRouteImport } from './routes/admin/billing/dashboard'
import { Route as AdminBillingSubscriptionIdRouteImport } from './routes/admin/billing/$subscriptionId'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings/members'
import { Route as AuthenticatedSettingsLookupsRouteImport } from './routes/_authenticated/settings/lookups'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedSettingsAuditLogRouteImport } from './routes/_authenticated/settings/audit-log'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedReportsSchedulesRouteImport } from './routes/_authenticated/reports/schedules'
import { Route as AuthenticatedReportsSavedRouteImport } from './routes/_authenticated/reports/saved'
import { Route as AuthenticatedReportsNewRouteImport } from './routes/_authenticated/reports/new'
import { Route as AuthenticatedNotificationsTemplatesRouteImport } from './routes/_authenticated/notifications/templates'
import { Route as AuthenticatedNotificationsPreferencesRouteImport } from './routes/_authenticated/notifications/preferences'
import { Route as AuthenticatedNotificationsDeliveriesRouteImport } from './routes/_authenticated/notifications/deliveries'
import { Route as AuthenticatedEimsSubmissionsRouteImport } from './routes/_authenticated/eims/submissions'
import { Route as AuthenticatedEimsSourcesRouteImport } from './routes/_authenticated/eims/sources'
import { Route as AuthenticatedEimsSetupRouteImport } from './routes/_authenticated/eims/setup'
import { Route as AuthenticatedEimsReceiptsRouteImport } from './routes/_authenticated/eims/receipts'
import { Route as AuthenticatedEimsEstablishmentsRouteImport } from './routes/_authenticated/eims/establishments'
import { Route as AuthenticatedEimsEnterprisesRouteImport } from './routes/_authenticated/eims/enterprises'
import { Route as AuthenticatedEimsCredentialsRouteImport } from './routes/_authenticated/eims/credentials'
import { Route as AuthenticatedEimsComplianceRouteImport } from './routes/_authenticated/eims/compliance'
import { Route as AuthenticatedEimsCertificatesRouteImport } from './routes/_authenticated/eims/certificates'
import { Route as AuthenticatedEimsBulkRouteImport } from './routes/_authenticated/eims/bulk'
import { Route as AuthenticatedReportsDashboardMainRouteImport } from './routes/_authenticated/reports/dashboard.main'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrgRoute = CreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemTemplatesIndexRoute =
  AdminSystemTemplatesIndexRouteImport.update({
    id: '/system-templates/',
    path: '/system-templates/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServerIndexRoute = AdminServerIndexRouteImport.update({
  id: '/server/',
  path: '/server/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansIndexRoute = AdminPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeatureFlagsIndexRoute = AdminFeatureFlagsIndexRouteImport.update({
  id: '/feature-flags/',
  path: '/feature-flags/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEimsIndexRoute = AdminEimsIndexRouteImport.update({
  id: '/eims/',
  path: '/eims/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingIndexRoute = AdminBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsIndexRoute = AdminAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesIndexRoute = AuthenticatedFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEimsIndexRoute = AuthenticatedEimsIndexRouteImport.update({
  id: '/eims/',
  path: '/eims/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminPlansNewRoute = AdminPlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansPlanIdRoute = AdminPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsOrgIdRoute = AdminOrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEimsTenantsRoute = AdminEimsTenantsRouteImport.update({
  id: '/eims/tenants',
  path: '/eims/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEimsResourcesRoute = AdminEimsResourcesRouteImport.update({
  id: '/eims/resources',
  path: '/eims/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEimsFailuresRoute = AdminEimsFailuresRouteImport.update({
  id: '/eims/failures',
  path: '/eims/failures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEimsComplianceRoute = AdminEimsComplianceRouteImport.update({
  id: '/eims/compliance',
  path: '/eims/compliance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEimsCertificatesRoute = AdminEimsCertificatesRouteImport.update({
  id: '/eims/certificates',
  path: '/eims/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingDashboardRoute = AdminBillingDashboardRouteImport.update({
  id: '/billing/dashboard',
  path: '/billing/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingSubscriptionIdRoute =
  AdminBillingSubscriptionIdRouteImport.update({
    id: '/billing/$subscriptionId',
    path: '/billing/$subscriptionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLookupsRoute =
  AuthenticatedSettingsLookupsRouteImport.update({
    id: '/settings/lookups',
    path: '/settings/lookups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAuditLogRoute =
  AuthenticatedSettingsAuditLogRouteImport.update({
    id: '/settings/audit-log',
    path: '/settings/audit-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsSchedulesRoute =
  AuthenticatedReportsSchedulesRouteImport.update({
    id: '/reports/schedules',
    path: '/reports/schedules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsSavedRoute =
  AuthenticatedReportsSavedRouteImport.update({
    id: '/reports/saved',
    path: '/reports/saved',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsNewRoute = AuthenticatedReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsTemplatesRoute =
  AuthenticatedNotificationsTemplatesRouteImport.update({
    id: '/notifications/templates',
    path: '/notifications/templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsPreferencesRoute =
  AuthenticatedNotificationsPreferencesRouteImport.update({
    id: '/notifications/preferences',
    path: '/notifications/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsDeliveriesRoute =
  AuthenticatedNotificationsDeliveriesRouteImport.update({
    id: '/notifications/deliveries',
    path: '/notifications/deliveries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEimsSubmissionsRoute =
  AuthenticatedEimsSubmissionsRouteImport.update({
    id: '/eims/submissions',
    path: '/eims/submissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEimsSourcesRoute =
  AuthenticatedEimsSourcesRouteImport.update({
    id: '/eims/sources',
    path: '/eims/sources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEimsSetupRoute = AuthenticatedEimsSetupRouteImport.update({
  id: '/eims/setup',
  path: '/eims/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEimsReceiptsRoute =
  AuthenticatedEimsReceiptsRouteImport.update({
    id: '/eims/receipts',
    path: '/eims/receipts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEimsEstablishmentsRoute =
  AuthenticatedEimsEstablishmentsRouteImport.update({
    id: '/eims/establishments',
    path: '/eims/establishments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEimsEnterprisesRoute =
  AuthenticatedEimsEnterprisesRouteImport.update({
    id: '/eims/enterprises',
    path: '/eims/enterprises',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEimsCredentialsRoute =
  AuthenticatedEimsCredentialsRouteImport.update({
    id: '/eims/credentials',
    path: '/eims/credentials',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEimsComplianceRoute =
  AuthenticatedEimsComplianceRouteImport.update({
    id: '/eims/compliance',
    path: '/eims/compliance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEimsCertificatesRoute =
  AuthenticatedEimsCertificatesRouteImport.update({
    id: '/eims/certificates',
    path: '/eims/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEimsBulkRoute = AuthenticatedEimsBulkRouteImport.update({
  id: '/eims/bulk',
  path: '/eims/bulk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsDashboardMainRoute =
  AuthenticatedReportsDashboardMainRouteImport.update({
    id: '/reports/dashboard/main',
    path: '/reports/dashboard/main',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/': typeof AdminIndexRoute
  '/eims/bulk': typeof AuthenticatedEimsBulkRoute
  '/eims/certificates': typeof AuthenticatedEimsCertificatesRoute
  '/eims/compliance': typeof AuthenticatedEimsComplianceRoute
  '/eims/credentials': typeof AuthenticatedEimsCredentialsRoute
  '/eims/enterprises': typeof AuthenticatedEimsEnterprisesRoute
  '/eims/establishments': typeof AuthenticatedEimsEstablishmentsRoute
  '/eims/receipts': typeof AuthenticatedEimsReceiptsRoute
  '/eims/setup': typeof AuthenticatedEimsSetupRoute
  '/eims/sources': typeof AuthenticatedEimsSourcesRoute
  '/eims/submissions': typeof AuthenticatedEimsSubmissionsRoute
  '/notifications/deliveries': typeof AuthenticatedNotificationsDeliveriesRoute
  '/notifications/preferences': typeof AuthenticatedNotificationsPreferencesRoute
  '/notifications/templates': typeof AuthenticatedNotificationsTemplatesRoute
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/reports/saved': typeof AuthenticatedReportsSavedRoute
  '/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/lookups': typeof AuthenticatedSettingsLookupsRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/admin/billing/$subscriptionId': typeof AdminBillingSubscriptionIdRoute
  '/admin/billing/dashboard': typeof AdminBillingDashboardRoute
  '/admin/eims/certificates': typeof AdminEimsCertificatesRoute
  '/admin/eims/compliance': typeof AdminEimsComplianceRoute
  '/admin/eims/failures': typeof AdminEimsFailuresRoute
  '/admin/eims/resources': typeof AdminEimsResourcesRoute
  '/admin/eims/tenants': typeof AdminEimsTenantsRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/plans/$planId': typeof AdminPlansPlanIdRoute
  '/admin/plans/new': typeof AdminPlansNewRoute
  '/eims/': typeof AuthenticatedEimsIndexRoute
  '/files/': typeof AuthenticatedFilesIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/admin/audit-logs/': typeof AdminAuditLogsIndexRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
  '/admin/eims/': typeof AdminEimsIndexRoute
  '/admin/feature-flags/': typeof AdminFeatureFlagsIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/plans/': typeof AdminPlansIndexRoute
  '/admin/server/': typeof AdminServerIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/system-templates/': typeof AdminSystemTemplatesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/reports/dashboard/main': typeof AuthenticatedReportsDashboardMainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminIndexRoute
  '/eims/bulk': typeof AuthenticatedEimsBulkRoute
  '/eims/certificates': typeof AuthenticatedEimsCertificatesRoute
  '/eims/compliance': typeof AuthenticatedEimsComplianceRoute
  '/eims/credentials': typeof AuthenticatedEimsCredentialsRoute
  '/eims/enterprises': typeof AuthenticatedEimsEnterprisesRoute
  '/eims/establishments': typeof AuthenticatedEimsEstablishmentsRoute
  '/eims/receipts': typeof AuthenticatedEimsReceiptsRoute
  '/eims/setup': typeof AuthenticatedEimsSetupRoute
  '/eims/sources': typeof AuthenticatedEimsSourcesRoute
  '/eims/submissions': typeof AuthenticatedEimsSubmissionsRoute
  '/notifications/deliveries': typeof AuthenticatedNotificationsDeliveriesRoute
  '/notifications/preferences': typeof AuthenticatedNotificationsPreferencesRoute
  '/notifications/templates': typeof AuthenticatedNotificationsTemplatesRoute
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/reports/saved': typeof AuthenticatedReportsSavedRoute
  '/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/lookups': typeof AuthenticatedSettingsLookupsRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/admin/billing/$subscriptionId': typeof AdminBillingSubscriptionIdRoute
  '/admin/billing/dashboard': typeof AdminBillingDashboardRoute
  '/admin/eims/certificates': typeof AdminEimsCertificatesRoute
  '/admin/eims/compliance': typeof AdminEimsComplianceRoute
  '/admin/eims/failures': typeof AdminEimsFailuresRoute
  '/admin/eims/resources': typeof AdminEimsResourcesRoute
  '/admin/eims/tenants': typeof AdminEimsTenantsRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/plans/$planId': typeof AdminPlansPlanIdRoute
  '/admin/plans/new': typeof AdminPlansNewRoute
  '/eims': typeof AuthenticatedEimsIndexRoute
  '/files': typeof AuthenticatedFilesIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/admin/audit-logs': typeof AdminAuditLogsIndexRoute
  '/admin/billing': typeof AdminBillingIndexRoute
  '/admin/eims': typeof AdminEimsIndexRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/plans': typeof AdminPlansIndexRoute
  '/admin/server': typeof AdminServerIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/system-templates': typeof AdminSystemTemplatesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/reports/dashboard/main': typeof AuthenticatedReportsDashboardMainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/eims/bulk': typeof AuthenticatedEimsBulkRoute
  '/_authenticated/eims/certificates': typeof AuthenticatedEimsCertificatesRoute
  '/_authenticated/eims/compliance': typeof AuthenticatedEimsComplianceRoute
  '/_authenticated/eims/credentials': typeof AuthenticatedEimsCredentialsRoute
  '/_authenticated/eims/enterprises': typeof AuthenticatedEimsEnterprisesRoute
  '/_authenticated/eims/establishments': typeof AuthenticatedEimsEstablishmentsRoute
  '/_authenticated/eims/receipts': typeof AuthenticatedEimsReceiptsRoute
  '/_authenticated/eims/setup': typeof AuthenticatedEimsSetupRoute
  '/_authenticated/eims/sources': typeof AuthenticatedEimsSourcesRoute
  '/_authenticated/eims/submissions': typeof AuthenticatedEimsSubmissionsRoute
  '/_authenticated/notifications/deliveries': typeof AuthenticatedNotificationsDeliveriesRoute
  '/_authenticated/notifications/preferences': typeof AuthenticatedNotificationsPreferencesRoute
  '/_authenticated/notifications/templates': typeof AuthenticatedNotificationsTemplatesRoute
  '/_authenticated/reports/new': typeof AuthenticatedReportsNewRoute
  '/_authenticated/reports/saved': typeof AuthenticatedReportsSavedRoute
  '/_authenticated/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/lookups': typeof AuthenticatedSettingsLookupsRoute
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/admin/billing/$subscriptionId': typeof AdminBillingSubscriptionIdRoute
  '/admin/billing/dashboard': typeof AdminBillingDashboardRoute
  '/admin/eims/certificates': typeof AdminEimsCertificatesRoute
  '/admin/eims/compliance': typeof AdminEimsComplianceRoute
  '/admin/eims/failures': typeof AdminEimsFailuresRoute
  '/admin/eims/resources': typeof AdminEimsResourcesRoute
  '/admin/eims/tenants': typeof AdminEimsTenantsRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/plans/$planId': typeof AdminPlansPlanIdRoute
  '/admin/plans/new': typeof AdminPlansNewRoute
  '/_authenticated/eims/': typeof AuthenticatedEimsIndexRoute
  '/_authenticated/files/': typeof AuthenticatedFilesIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/admin/audit-logs/': typeof AdminAuditLogsIndexRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
  '/admin/eims/': typeof AdminEimsIndexRoute
  '/admin/feature-flags/': typeof AdminFeatureFlagsIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/plans/': typeof AdminPlansIndexRoute
  '/admin/server/': typeof AdminServerIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/system-templates/': typeof AdminSystemTemplatesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_authenticated/reports/dashboard/main': typeof AuthenticatedReportsDashboardMainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/create-org'
    | '/login'
    | '/signup'
    | '/admin/'
    | '/eims/bulk'
    | '/eims/certificates'
    | '/eims/compliance'
    | '/eims/credentials'
    | '/eims/enterprises'
    | '/eims/establishments'
    | '/eims/receipts'
    | '/eims/setup'
    | '/eims/sources'
    | '/eims/submissions'
    | '/notifications/deliveries'
    | '/notifications/preferences'
    | '/notifications/templates'
    | '/reports/new'
    | '/reports/saved'
    | '/reports/schedules'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/lookups'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/roles'
    | '/settings/security'
    | '/admin/billing/$subscriptionId'
    | '/admin/billing/dashboard'
    | '/admin/eims/certificates'
    | '/admin/eims/compliance'
    | '/admin/eims/failures'
    | '/admin/eims/resources'
    | '/admin/eims/tenants'
    | '/admin/organizations/$orgId'
    | '/admin/plans/$planId'
    | '/admin/plans/new'
    | '/eims/'
    | '/files/'
    | '/notifications/'
    | '/reports/'
    | '/settings/'
    | '/admin/audit-logs/'
    | '/admin/billing/'
    | '/admin/eims/'
    | '/admin/feature-flags/'
    | '/admin/jobs/'
    | '/admin/organizations/'
    | '/admin/plans/'
    | '/admin/server/'
    | '/admin/settings/'
    | '/admin/system-templates/'
    | '/admin/users/'
    | '/reports/dashboard/main'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/create-org'
    | '/login'
    | '/signup'
    | '/admin'
    | '/eims/bulk'
    | '/eims/certificates'
    | '/eims/compliance'
    | '/eims/credentials'
    | '/eims/enterprises'
    | '/eims/establishments'
    | '/eims/receipts'
    | '/eims/setup'
    | '/eims/sources'
    | '/eims/submissions'
    | '/notifications/deliveries'
    | '/notifications/preferences'
    | '/notifications/templates'
    | '/reports/new'
    | '/reports/saved'
    | '/reports/schedules'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/lookups'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/roles'
    | '/settings/security'
    | '/admin/billing/$subscriptionId'
    | '/admin/billing/dashboard'
    | '/admin/eims/certificates'
    | '/admin/eims/compliance'
    | '/admin/eims/failures'
    | '/admin/eims/resources'
    | '/admin/eims/tenants'
    | '/admin/organizations/$orgId'
    | '/admin/plans/$planId'
    | '/admin/plans/new'
    | '/eims'
    | '/files'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/billing'
    | '/admin/eims'
    | '/admin/feature-flags'
    | '/admin/jobs'
    | '/admin/organizations'
    | '/admin/plans'
    | '/admin/server'
    | '/admin/settings'
    | '/admin/system-templates'
    | '/admin/users'
    | '/reports/dashboard/main'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-login'
    | '/create-org'
    | '/login'
    | '/signup'
    | '/admin/'
    | '/_authenticated/eims/bulk'
    | '/_authenticated/eims/certificates'
    | '/_authenticated/eims/compliance'
    | '/_authenticated/eims/credentials'
    | '/_authenticated/eims/enterprises'
    | '/_authenticated/eims/establishments'
    | '/_authenticated/eims/receipts'
    | '/_authenticated/eims/setup'
    | '/_authenticated/eims/sources'
    | '/_authenticated/eims/submissions'
    | '/_authenticated/notifications/deliveries'
    | '/_authenticated/notifications/preferences'
    | '/_authenticated/notifications/templates'
    | '/_authenticated/reports/new'
    | '/_authenticated/reports/saved'
    | '/_authenticated/reports/schedules'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/audit-log'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/lookups'
    | '/_authenticated/settings/members'
    | '/_authenticated/settings/organization'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/security'
    | '/admin/billing/$subscriptionId'
    | '/admin/billing/dashboard'
    | '/admin/eims/certificates'
    | '/admin/eims/compliance'
    | '/admin/eims/failures'
    | '/admin/eims/resources'
    | '/admin/eims/tenants'
    | '/admin/organizations/$orgId'
    | '/admin/plans/$planId'
    | '/admin/plans/new'
    | '/_authenticated/eims/'
    | '/_authenticated/files/'
    | '/_authenticated/notifications/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/admin/audit-logs/'
    | '/admin/billing/'
    | '/admin/eims/'
    | '/admin/feature-flags/'
    | '/admin/jobs/'
    | '/admin/organizations/'
    | '/admin/plans/'
    | '/admin/server/'
    | '/admin/settings/'
    | '/admin/system-templates/'
    | '/admin/users/'
    | '/_authenticated/reports/dashboard/main'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CreateOrgRoute: typeof CreateOrgRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-templates/': {
      id: '/admin/system-templates/'
      path: '/system-templates'
      fullPath: '/admin/system-templates/'
      preLoaderRoute: typeof AdminSystemTemplatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/server/': {
      id: '/admin/server/'
      path: '/server'
      fullPath: '/admin/server/'
      preLoaderRoute: typeof AdminServerIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans/': {
      id: '/admin/plans/'
      path: '/plans'
      fullPath: '/admin/plans/'
      preLoaderRoute: typeof AdminPlansIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feature-flags/': {
      id: '/admin/feature-flags/'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags/'
      preLoaderRoute: typeof AdminFeatureFlagsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eims/': {
      id: '/admin/eims/'
      path: '/eims'
      fullPath: '/admin/eims/'
      preLoaderRoute: typeof AdminEimsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing/': {
      id: '/admin/billing/'
      path: '/billing'
      fullPath: '/admin/billing/'
      preLoaderRoute: typeof AdminBillingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs/': {
      id: '/admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof AdminAuditLogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/files/': {
      id: '/_authenticated/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof AuthenticatedFilesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/': {
      id: '/_authenticated/eims/'
      path: '/eims'
      fullPath: '/eims/'
      preLoaderRoute: typeof AuthenticatedEimsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/plans/new': {
      id: '/admin/plans/new'
      path: '/plans/new'
      fullPath: '/admin/plans/new'
      preLoaderRoute: typeof AdminPlansNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans/$planId': {
      id: '/admin/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/admin/plans/$planId'
      preLoaderRoute: typeof AdminPlansPlanIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/$orgId': {
      id: '/admin/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/admin/organizations/$orgId'
      preLoaderRoute: typeof AdminOrganizationsOrgIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eims/tenants': {
      id: '/admin/eims/tenants'
      path: '/eims/tenants'
      fullPath: '/admin/eims/tenants'
      preLoaderRoute: typeof AdminEimsTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eims/resources': {
      id: '/admin/eims/resources'
      path: '/eims/resources'
      fullPath: '/admin/eims/resources'
      preLoaderRoute: typeof AdminEimsResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eims/failures': {
      id: '/admin/eims/failures'
      path: '/eims/failures'
      fullPath: '/admin/eims/failures'
      preLoaderRoute: typeof AdminEimsFailuresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eims/compliance': {
      id: '/admin/eims/compliance'
      path: '/eims/compliance'
      fullPath: '/admin/eims/compliance'
      preLoaderRoute: typeof AdminEimsComplianceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eims/certificates': {
      id: '/admin/eims/certificates'
      path: '/eims/certificates'
      fullPath: '/admin/eims/certificates'
      preLoaderRoute: typeof AdminEimsCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing/dashboard': {
      id: '/admin/billing/dashboard'
      path: '/billing/dashboard'
      fullPath: '/admin/billing/dashboard'
      preLoaderRoute: typeof AdminBillingDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing/$subscriptionId': {
      id: '/admin/billing/$subscriptionId'
      path: '/billing/$subscriptionId'
      fullPath: '/admin/billing/$subscriptionId'
      preLoaderRoute: typeof AdminBillingSubscriptionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/lookups': {
      id: '/_authenticated/settings/lookups'
      path: '/settings/lookups'
      fullPath: '/settings/lookups'
      preLoaderRoute: typeof AuthenticatedSettingsLookupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/audit-log': {
      id: '/_authenticated/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AuthenticatedSettingsAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/schedules': {
      id: '/_authenticated/reports/schedules'
      path: '/reports/schedules'
      fullPath: '/reports/schedules'
      preLoaderRoute: typeof AuthenticatedReportsSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/saved': {
      id: '/_authenticated/reports/saved'
      path: '/reports/saved'
      fullPath: '/reports/saved'
      preLoaderRoute: typeof AuthenticatedReportsSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/new': {
      id: '/_authenticated/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AuthenticatedReportsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/templates': {
      id: '/_authenticated/notifications/templates'
      path: '/notifications/templates'
      fullPath: '/notifications/templates'
      preLoaderRoute: typeof AuthenticatedNotificationsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/preferences': {
      id: '/_authenticated/notifications/preferences'
      path: '/notifications/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof AuthenticatedNotificationsPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/deliveries': {
      id: '/_authenticated/notifications/deliveries'
      path: '/notifications/deliveries'
      fullPath: '/notifications/deliveries'
      preLoaderRoute: typeof AuthenticatedNotificationsDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/submissions': {
      id: '/_authenticated/eims/submissions'
      path: '/eims/submissions'
      fullPath: '/eims/submissions'
      preLoaderRoute: typeof AuthenticatedEimsSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/sources': {
      id: '/_authenticated/eims/sources'
      path: '/eims/sources'
      fullPath: '/eims/sources'
      preLoaderRoute: typeof AuthenticatedEimsSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/setup': {
      id: '/_authenticated/eims/setup'
      path: '/eims/setup'
      fullPath: '/eims/setup'
      preLoaderRoute: typeof AuthenticatedEimsSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/receipts': {
      id: '/_authenticated/eims/receipts'
      path: '/eims/receipts'
      fullPath: '/eims/receipts'
      preLoaderRoute: typeof AuthenticatedEimsReceiptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/establishments': {
      id: '/_authenticated/eims/establishments'
      path: '/eims/establishments'
      fullPath: '/eims/establishments'
      preLoaderRoute: typeof AuthenticatedEimsEstablishmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/enterprises': {
      id: '/_authenticated/eims/enterprises'
      path: '/eims/enterprises'
      fullPath: '/eims/enterprises'
      preLoaderRoute: typeof AuthenticatedEimsEnterprisesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/credentials': {
      id: '/_authenticated/eims/credentials'
      path: '/eims/credentials'
      fullPath: '/eims/credentials'
      preLoaderRoute: typeof AuthenticatedEimsCredentialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/compliance': {
      id: '/_authenticated/eims/compliance'
      path: '/eims/compliance'
      fullPath: '/eims/compliance'
      preLoaderRoute: typeof AuthenticatedEimsComplianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/certificates': {
      id: '/_authenticated/eims/certificates'
      path: '/eims/certificates'
      fullPath: '/eims/certificates'
      preLoaderRoute: typeof AuthenticatedEimsCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eims/bulk': {
      id: '/_authenticated/eims/bulk'
      path: '/eims/bulk'
      fullPath: '/eims/bulk'
      preLoaderRoute: typeof AuthenticatedEimsBulkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/dashboard/main': {
      id: '/_authenticated/reports/dashboard/main'
      path: '/reports/dashboard/main'
      fullPath: '/reports/dashboard/main'
      preLoaderRoute: typeof AuthenticatedReportsDashboardMainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEimsBulkRoute: typeof AuthenticatedEimsBulkRoute
  AuthenticatedEimsCertificatesRoute: typeof AuthenticatedEimsCertificatesRoute
  AuthenticatedEimsComplianceRoute: typeof AuthenticatedEimsComplianceRoute
  AuthenticatedEimsCredentialsRoute: typeof AuthenticatedEimsCredentialsRoute
  AuthenticatedEimsEnterprisesRoute: typeof AuthenticatedEimsEnterprisesRoute
  AuthenticatedEimsEstablishmentsRoute: typeof AuthenticatedEimsEstablishmentsRoute
  AuthenticatedEimsReceiptsRoute: typeof AuthenticatedEimsReceiptsRoute
  AuthenticatedEimsSetupRoute: typeof AuthenticatedEimsSetupRoute
  AuthenticatedEimsSourcesRoute: typeof AuthenticatedEimsSourcesRoute
  AuthenticatedEimsSubmissionsRoute: typeof AuthenticatedEimsSubmissionsRoute
  AuthenticatedNotificationsDeliveriesRoute: typeof AuthenticatedNotificationsDeliveriesRoute
  AuthenticatedNotificationsPreferencesRoute: typeof AuthenticatedNotificationsPreferencesRoute
  AuthenticatedNotificationsTemplatesRoute: typeof AuthenticatedNotificationsTemplatesRoute
  AuthenticatedReportsNewRoute: typeof AuthenticatedReportsNewRoute
  AuthenticatedReportsSavedRoute: typeof AuthenticatedReportsSavedRoute
  AuthenticatedReportsSchedulesRoute: typeof AuthenticatedReportsSchedulesRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAuditLogRoute: typeof AuthenticatedSettingsAuditLogRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsLookupsRoute: typeof AuthenticatedSettingsLookupsRoute
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedEimsIndexRoute: typeof AuthenticatedEimsIndexRoute
  AuthenticatedFilesIndexRoute: typeof AuthenticatedFilesIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedReportsDashboardMainRoute: typeof AuthenticatedReportsDashboardMainRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEimsBulkRoute: AuthenticatedEimsBulkRoute,
  AuthenticatedEimsCertificatesRoute: AuthenticatedEimsCertificatesRoute,
  AuthenticatedEimsComplianceRoute: AuthenticatedEimsComplianceRoute,
  AuthenticatedEimsCredentialsRoute: AuthenticatedEimsCredentialsRoute,
  AuthenticatedEimsEnterprisesRoute: AuthenticatedEimsEnterprisesRoute,
  AuthenticatedEimsEstablishmentsRoute: AuthenticatedEimsEstablishmentsRoute,
  AuthenticatedEimsReceiptsRoute: AuthenticatedEimsReceiptsRoute,
  AuthenticatedEimsSetupRoute: AuthenticatedEimsSetupRoute,
  AuthenticatedEimsSourcesRoute: AuthenticatedEimsSourcesRoute,
  AuthenticatedEimsSubmissionsRoute: AuthenticatedEimsSubmissionsRoute,
  AuthenticatedNotificationsDeliveriesRoute:
    AuthenticatedNotificationsDeliveriesRoute,
  AuthenticatedNotificationsPreferencesRoute:
    AuthenticatedNotificationsPreferencesRoute,
  AuthenticatedNotificationsTemplatesRoute:
    AuthenticatedNotificationsTemplatesRoute,
  AuthenticatedReportsNewRoute: AuthenticatedReportsNewRoute,
  AuthenticatedReportsSavedRoute: AuthenticatedReportsSavedRoute,
  AuthenticatedReportsSchedulesRoute: AuthenticatedReportsSchedulesRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsAuditLogRoute: AuthenticatedSettingsAuditLogRoute,
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsLookupsRoute: AuthenticatedSettingsLookupsRoute,
  AuthenticatedSettingsMembersRoute: AuthenticatedSettingsMembersRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedEimsIndexRoute: AuthenticatedEimsIndexRoute,
  AuthenticatedFilesIndexRoute: AuthenticatedFilesIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedReportsDashboardMainRoute:
    AuthenticatedReportsDashboardMainRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBillingSubscriptionIdRoute: typeof AdminBillingSubscriptionIdRoute
  AdminBillingDashboardRoute: typeof AdminBillingDashboardRoute
  AdminEimsCertificatesRoute: typeof AdminEimsCertificatesRoute
  AdminEimsComplianceRoute: typeof AdminEimsComplianceRoute
  AdminEimsFailuresRoute: typeof AdminEimsFailuresRoute
  AdminEimsResourcesRoute: typeof AdminEimsResourcesRoute
  AdminEimsTenantsRoute: typeof AdminEimsTenantsRoute
  AdminOrganizationsOrgIdRoute: typeof AdminOrganizationsOrgIdRoute
  AdminPlansPlanIdRoute: typeof AdminPlansPlanIdRoute
  AdminPlansNewRoute: typeof AdminPlansNewRoute
  AdminAuditLogsIndexRoute: typeof AdminAuditLogsIndexRoute
  AdminBillingIndexRoute: typeof AdminBillingIndexRoute
  AdminEimsIndexRoute: typeof AdminEimsIndexRoute
  AdminFeatureFlagsIndexRoute: typeof AdminFeatureFlagsIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminPlansIndexRoute: typeof AdminPlansIndexRoute
  AdminServerIndexRoute: typeof AdminServerIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSystemTemplatesIndexRoute: typeof AdminSystemTemplatesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBillingSubscriptionIdRoute: AdminBillingSubscriptionIdRoute,
  AdminBillingDashboardRoute: AdminBillingDashboardRoute,
  AdminEimsCertificatesRoute: AdminEimsCertificatesRoute,
  AdminEimsComplianceRoute: AdminEimsComplianceRoute,
  AdminEimsFailuresRoute: AdminEimsFailuresRoute,
  AdminEimsResourcesRoute: AdminEimsResourcesRoute,
  AdminEimsTenantsRoute: AdminEimsTenantsRoute,
  AdminOrganizationsOrgIdRoute: AdminOrganizationsOrgIdRoute,
  AdminPlansPlanIdRoute: AdminPlansPlanIdRoute,
  AdminPlansNewRoute: AdminPlansNewRoute,
  AdminAuditLogsIndexRoute: AdminAuditLogsIndexRoute,
  AdminBillingIndexRoute: AdminBillingIndexRoute,
  AdminEimsIndexRoute: AdminEimsIndexRoute,
  AdminFeatureFlagsIndexRoute: AdminFeatureFlagsIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminPlansIndexRoute: AdminPlansIndexRoute,
  AdminServerIndexRoute: AdminServerIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSystemTemplatesIndexRoute: AdminSystemTemplatesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CreateOrgRoute: CreateOrgRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
