/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateOrgRouteImport } from './routes/create-org'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSystemTemplatesIndexRouteImport } from './routes/admin/system-templates/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminServerIndexRouteImport } from './routes/admin/server/index'
import { Route as AdminPlansIndexRouteImport } from './routes/admin/plans/index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as AdminOnboardingIndexRouteImport } from './routes/admin/onboarding/index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminFeatureFlagsIndexRouteImport } from './routes/admin/feature-flags/index'
import { Route as AdminBillingIndexRouteImport } from './routes/admin/billing/index'
import { Route as AdminAuditLogsIndexRouteImport } from './routes/admin/audit-logs/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedFilesIndexRouteImport } from './routes/_authenticated/files/index'
import { Route as AdminPlansNewRouteImport } from './routes/admin/plans/new'
import { Route as AdminPlansPlanIdRouteImport } from './routes/admin/plans/$planId'
import { Route as AdminOrganizationsOrgIdRouteImport } from './routes/admin/organizations/$orgId'
import { Route as AdminOnboardingNewRouteImport } from './routes/admin/onboarding/new'
import { Route as AdminOnboardingTaskIdRouteImport } from './routes/admin/onboarding/$taskId'
import { Route as AdminBillingDashboardRouteImport } from './routes/admin/billing/dashboard'
import { Route as AdminBillingSubscriptionIdRouteImport } from './routes/admin/billing/$subscriptionId'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings/members'
import { Route as AuthenticatedSettingsLookupsRouteImport } from './routes/_authenticated/settings/lookups'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedSettingsAuditLogRouteImport } from './routes/_authenticated/settings/audit-log'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedReportsSchedulesRouteImport } from './routes/_authenticated/reports/schedules'
import { Route as AuthenticatedReportsSavedRouteImport } from './routes/_authenticated/reports/saved'
import { Route as AuthenticatedReportsNewRouteImport } from './routes/_authenticated/reports/new'
import { Route as AuthenticatedNotificationsTemplatesRouteImport } from './routes/_authenticated/notifications/templates'
import { Route as AuthenticatedNotificationsPreferencesRouteImport } from './routes/_authenticated/notifications/preferences'
import { Route as AuthenticatedNotificationsDeliveriesRouteImport } from './routes/_authenticated/notifications/deliveries'
import { Route as AuthenticatedReportsDashboardMainRouteImport } from './routes/_authenticated/reports/dashboard.main'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrgRoute = CreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemTemplatesIndexRoute =
  AdminSystemTemplatesIndexRouteImport.update({
    id: '/system-templates/',
    path: '/system-templates/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServerIndexRoute = AdminServerIndexRouteImport.update({
  id: '/server/',
  path: '/server/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansIndexRoute = AdminPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingIndexRoute = AdminOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeatureFlagsIndexRoute = AdminFeatureFlagsIndexRouteImport.update({
  id: '/feature-flags/',
  path: '/feature-flags/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingIndexRoute = AdminBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsIndexRoute = AdminAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesIndexRoute = AuthenticatedFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminPlansNewRoute = AdminPlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansPlanIdRoute = AdminPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsOrgIdRoute = AdminOrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingNewRoute = AdminOnboardingNewRouteImport.update({
  id: '/onboarding/new',
  path: '/onboarding/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingTaskIdRoute = AdminOnboardingTaskIdRouteImport.update({
  id: '/onboarding/$taskId',
  path: '/onboarding/$taskId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingDashboardRoute = AdminBillingDashboardRouteImport.update({
  id: '/billing/dashboard',
  path: '/billing/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingSubscriptionIdRoute =
  AdminBillingSubscriptionIdRouteImport.update({
    id: '/billing/$subscriptionId',
    path: '/billing/$subscriptionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLookupsRoute =
  AuthenticatedSettingsLookupsRouteImport.update({
    id: '/settings/lookups',
    path: '/settings/lookups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAuditLogRoute =
  AuthenticatedSettingsAuditLogRouteImport.update({
    id: '/settings/audit-log',
    path: '/settings/audit-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsSchedulesRoute =
  AuthenticatedReportsSchedulesRouteImport.update({
    id: '/reports/schedules',
    path: '/reports/schedules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsSavedRoute =
  AuthenticatedReportsSavedRouteImport.update({
    id: '/reports/saved',
    path: '/reports/saved',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsNewRoute = AuthenticatedReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsTemplatesRoute =
  AuthenticatedNotificationsTemplatesRouteImport.update({
    id: '/notifications/templates',
    path: '/notifications/templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsPreferencesRoute =
  AuthenticatedNotificationsPreferencesRouteImport.update({
    id: '/notifications/preferences',
    path: '/notifications/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsDeliveriesRoute =
  AuthenticatedNotificationsDeliveriesRouteImport.update({
    id: '/notifications/deliveries',
    path: '/notifications/deliveries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsDashboardMainRoute =
  AuthenticatedReportsDashboardMainRouteImport.update({
    id: '/reports/dashboard/main',
    path: '/reports/dashboard/main',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/': typeof AdminIndexRoute
  '/notifications/deliveries': typeof AuthenticatedNotificationsDeliveriesRoute
  '/notifications/preferences': typeof AuthenticatedNotificationsPreferencesRoute
  '/notifications/templates': typeof AuthenticatedNotificationsTemplatesRoute
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/reports/saved': typeof AuthenticatedReportsSavedRoute
  '/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/lookups': typeof AuthenticatedSettingsLookupsRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/admin/billing/$subscriptionId': typeof AdminBillingSubscriptionIdRoute
  '/admin/billing/dashboard': typeof AdminBillingDashboardRoute
  '/admin/onboarding/$taskId': typeof AdminOnboardingTaskIdRoute
  '/admin/onboarding/new': typeof AdminOnboardingNewRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/plans/$planId': typeof AdminPlansPlanIdRoute
  '/admin/plans/new': typeof AdminPlansNewRoute
  '/files/': typeof AuthenticatedFilesIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/admin/audit-logs/': typeof AdminAuditLogsIndexRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
  '/admin/feature-flags/': typeof AdminFeatureFlagsIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/onboarding/': typeof AdminOnboardingIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/plans/': typeof AdminPlansIndexRoute
  '/admin/server/': typeof AdminServerIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/system-templates/': typeof AdminSystemTemplatesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/reports/dashboard/main': typeof AuthenticatedReportsDashboardMainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminIndexRoute
  '/notifications/deliveries': typeof AuthenticatedNotificationsDeliveriesRoute
  '/notifications/preferences': typeof AuthenticatedNotificationsPreferencesRoute
  '/notifications/templates': typeof AuthenticatedNotificationsTemplatesRoute
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/reports/saved': typeof AuthenticatedReportsSavedRoute
  '/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/lookups': typeof AuthenticatedSettingsLookupsRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/admin/billing/$subscriptionId': typeof AdminBillingSubscriptionIdRoute
  '/admin/billing/dashboard': typeof AdminBillingDashboardRoute
  '/admin/onboarding/$taskId': typeof AdminOnboardingTaskIdRoute
  '/admin/onboarding/new': typeof AdminOnboardingNewRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/plans/$planId': typeof AdminPlansPlanIdRoute
  '/admin/plans/new': typeof AdminPlansNewRoute
  '/files': typeof AuthenticatedFilesIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/admin/audit-logs': typeof AdminAuditLogsIndexRoute
  '/admin/billing': typeof AdminBillingIndexRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/onboarding': typeof AdminOnboardingIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/plans': typeof AdminPlansIndexRoute
  '/admin/server': typeof AdminServerIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/system-templates': typeof AdminSystemTemplatesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/reports/dashboard/main': typeof AuthenticatedReportsDashboardMainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/notifications/deliveries': typeof AuthenticatedNotificationsDeliveriesRoute
  '/_authenticated/notifications/preferences': typeof AuthenticatedNotificationsPreferencesRoute
  '/_authenticated/notifications/templates': typeof AuthenticatedNotificationsTemplatesRoute
  '/_authenticated/reports/new': typeof AuthenticatedReportsNewRoute
  '/_authenticated/reports/saved': typeof AuthenticatedReportsSavedRoute
  '/_authenticated/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/lookups': typeof AuthenticatedSettingsLookupsRoute
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/admin/billing/$subscriptionId': typeof AdminBillingSubscriptionIdRoute
  '/admin/billing/dashboard': typeof AdminBillingDashboardRoute
  '/admin/onboarding/$taskId': typeof AdminOnboardingTaskIdRoute
  '/admin/onboarding/new': typeof AdminOnboardingNewRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/plans/$planId': typeof AdminPlansPlanIdRoute
  '/admin/plans/new': typeof AdminPlansNewRoute
  '/_authenticated/files/': typeof AuthenticatedFilesIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/admin/audit-logs/': typeof AdminAuditLogsIndexRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
  '/admin/feature-flags/': typeof AdminFeatureFlagsIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/onboarding/': typeof AdminOnboardingIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/plans/': typeof AdminPlansIndexRoute
  '/admin/server/': typeof AdminServerIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/system-templates/': typeof AdminSystemTemplatesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_authenticated/reports/dashboard/main': typeof AuthenticatedReportsDashboardMainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/create-org'
    | '/login'
    | '/signup'
    | '/admin/'
    | '/notifications/deliveries'
    | '/notifications/preferences'
    | '/notifications/templates'
    | '/reports/new'
    | '/reports/saved'
    | '/reports/schedules'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/lookups'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/roles'
    | '/settings/security'
    | '/admin/billing/$subscriptionId'
    | '/admin/billing/dashboard'
    | '/admin/onboarding/$taskId'
    | '/admin/onboarding/new'
    | '/admin/organizations/$orgId'
    | '/admin/plans/$planId'
    | '/admin/plans/new'
    | '/files/'
    | '/notifications/'
    | '/onboarding/'
    | '/reports/'
    | '/settings/'
    | '/admin/audit-logs/'
    | '/admin/billing/'
    | '/admin/feature-flags/'
    | '/admin/jobs/'
    | '/admin/onboarding/'
    | '/admin/organizations/'
    | '/admin/plans/'
    | '/admin/server/'
    | '/admin/settings/'
    | '/admin/system-templates/'
    | '/admin/users/'
    | '/reports/dashboard/main'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/create-org'
    | '/login'
    | '/signup'
    | '/admin'
    | '/notifications/deliveries'
    | '/notifications/preferences'
    | '/notifications/templates'
    | '/reports/new'
    | '/reports/saved'
    | '/reports/schedules'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/lookups'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/roles'
    | '/settings/security'
    | '/admin/billing/$subscriptionId'
    | '/admin/billing/dashboard'
    | '/admin/onboarding/$taskId'
    | '/admin/onboarding/new'
    | '/admin/organizations/$orgId'
    | '/admin/plans/$planId'
    | '/admin/plans/new'
    | '/files'
    | '/notifications'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/billing'
    | '/admin/feature-flags'
    | '/admin/jobs'
    | '/admin/onboarding'
    | '/admin/organizations'
    | '/admin/plans'
    | '/admin/server'
    | '/admin/settings'
    | '/admin/system-templates'
    | '/admin/users'
    | '/reports/dashboard/main'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-login'
    | '/create-org'
    | '/login'
    | '/signup'
    | '/admin/'
    | '/_authenticated/notifications/deliveries'
    | '/_authenticated/notifications/preferences'
    | '/_authenticated/notifications/templates'
    | '/_authenticated/reports/new'
    | '/_authenticated/reports/saved'
    | '/_authenticated/reports/schedules'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/audit-log'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/lookups'
    | '/_authenticated/settings/members'
    | '/_authenticated/settings/organization'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/security'
    | '/admin/billing/$subscriptionId'
    | '/admin/billing/dashboard'
    | '/admin/onboarding/$taskId'
    | '/admin/onboarding/new'
    | '/admin/organizations/$orgId'
    | '/admin/plans/$planId'
    | '/admin/plans/new'
    | '/_authenticated/files/'
    | '/_authenticated/notifications/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/admin/audit-logs/'
    | '/admin/billing/'
    | '/admin/feature-flags/'
    | '/admin/jobs/'
    | '/admin/onboarding/'
    | '/admin/organizations/'
    | '/admin/plans/'
    | '/admin/server/'
    | '/admin/settings/'
    | '/admin/system-templates/'
    | '/admin/users/'
    | '/_authenticated/reports/dashboard/main'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CreateOrgRoute: typeof CreateOrgRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-templates/': {
      id: '/admin/system-templates/'
      path: '/system-templates'
      fullPath: '/admin/system-templates/'
      preLoaderRoute: typeof AdminSystemTemplatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/server/': {
      id: '/admin/server/'
      path: '/server'
      fullPath: '/admin/server/'
      preLoaderRoute: typeof AdminServerIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans/': {
      id: '/admin/plans/'
      path: '/plans'
      fullPath: '/admin/plans/'
      preLoaderRoute: typeof AdminPlansIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding/': {
      id: '/admin/onboarding/'
      path: '/onboarding'
      fullPath: '/admin/onboarding/'
      preLoaderRoute: typeof AdminOnboardingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feature-flags/': {
      id: '/admin/feature-flags/'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags/'
      preLoaderRoute: typeof AdminFeatureFlagsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing/': {
      id: '/admin/billing/'
      path: '/billing'
      fullPath: '/admin/billing/'
      preLoaderRoute: typeof AdminBillingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs/': {
      id: '/admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof AdminAuditLogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/files/': {
      id: '/_authenticated/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof AuthenticatedFilesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/plans/new': {
      id: '/admin/plans/new'
      path: '/plans/new'
      fullPath: '/admin/plans/new'
      preLoaderRoute: typeof AdminPlansNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans/$planId': {
      id: '/admin/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/admin/plans/$planId'
      preLoaderRoute: typeof AdminPlansPlanIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/$orgId': {
      id: '/admin/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/admin/organizations/$orgId'
      preLoaderRoute: typeof AdminOrganizationsOrgIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding/new': {
      id: '/admin/onboarding/new'
      path: '/onboarding/new'
      fullPath: '/admin/onboarding/new'
      preLoaderRoute: typeof AdminOnboardingNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding/$taskId': {
      id: '/admin/onboarding/$taskId'
      path: '/onboarding/$taskId'
      fullPath: '/admin/onboarding/$taskId'
      preLoaderRoute: typeof AdminOnboardingTaskIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing/dashboard': {
      id: '/admin/billing/dashboard'
      path: '/billing/dashboard'
      fullPath: '/admin/billing/dashboard'
      preLoaderRoute: typeof AdminBillingDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing/$subscriptionId': {
      id: '/admin/billing/$subscriptionId'
      path: '/billing/$subscriptionId'
      fullPath: '/admin/billing/$subscriptionId'
      preLoaderRoute: typeof AdminBillingSubscriptionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/lookups': {
      id: '/_authenticated/settings/lookups'
      path: '/settings/lookups'
      fullPath: '/settings/lookups'
      preLoaderRoute: typeof AuthenticatedSettingsLookupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/audit-log': {
      id: '/_authenticated/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AuthenticatedSettingsAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/schedules': {
      id: '/_authenticated/reports/schedules'
      path: '/reports/schedules'
      fullPath: '/reports/schedules'
      preLoaderRoute: typeof AuthenticatedReportsSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/saved': {
      id: '/_authenticated/reports/saved'
      path: '/reports/saved'
      fullPath: '/reports/saved'
      preLoaderRoute: typeof AuthenticatedReportsSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/new': {
      id: '/_authenticated/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AuthenticatedReportsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/templates': {
      id: '/_authenticated/notifications/templates'
      path: '/notifications/templates'
      fullPath: '/notifications/templates'
      preLoaderRoute: typeof AuthenticatedNotificationsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/preferences': {
      id: '/_authenticated/notifications/preferences'
      path: '/notifications/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof AuthenticatedNotificationsPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/deliveries': {
      id: '/_authenticated/notifications/deliveries'
      path: '/notifications/deliveries'
      fullPath: '/notifications/deliveries'
      preLoaderRoute: typeof AuthenticatedNotificationsDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/dashboard/main': {
      id: '/_authenticated/reports/dashboard/main'
      path: '/reports/dashboard/main'
      fullPath: '/reports/dashboard/main'
      preLoaderRoute: typeof AuthenticatedReportsDashboardMainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedNotificationsDeliveriesRoute: typeof AuthenticatedNotificationsDeliveriesRoute
  AuthenticatedNotificationsPreferencesRoute: typeof AuthenticatedNotificationsPreferencesRoute
  AuthenticatedNotificationsTemplatesRoute: typeof AuthenticatedNotificationsTemplatesRoute
  AuthenticatedReportsNewRoute: typeof AuthenticatedReportsNewRoute
  AuthenticatedReportsSavedRoute: typeof AuthenticatedReportsSavedRoute
  AuthenticatedReportsSchedulesRoute: typeof AuthenticatedReportsSchedulesRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAuditLogRoute: typeof AuthenticatedSettingsAuditLogRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsLookupsRoute: typeof AuthenticatedSettingsLookupsRoute
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedFilesIndexRoute: typeof AuthenticatedFilesIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedReportsDashboardMainRoute: typeof AuthenticatedReportsDashboardMainRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNotificationsDeliveriesRoute:
    AuthenticatedNotificationsDeliveriesRoute,
  AuthenticatedNotificationsPreferencesRoute:
    AuthenticatedNotificationsPreferencesRoute,
  AuthenticatedNotificationsTemplatesRoute:
    AuthenticatedNotificationsTemplatesRoute,
  AuthenticatedReportsNewRoute: AuthenticatedReportsNewRoute,
  AuthenticatedReportsSavedRoute: AuthenticatedReportsSavedRoute,
  AuthenticatedReportsSchedulesRoute: AuthenticatedReportsSchedulesRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsAuditLogRoute: AuthenticatedSettingsAuditLogRoute,
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsLookupsRoute: AuthenticatedSettingsLookupsRoute,
  AuthenticatedSettingsMembersRoute: AuthenticatedSettingsMembersRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedFilesIndexRoute: AuthenticatedFilesIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedReportsDashboardMainRoute:
    AuthenticatedReportsDashboardMainRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBillingSubscriptionIdRoute: typeof AdminBillingSubscriptionIdRoute
  AdminBillingDashboardRoute: typeof AdminBillingDashboardRoute
  AdminOnboardingTaskIdRoute: typeof AdminOnboardingTaskIdRoute
  AdminOnboardingNewRoute: typeof AdminOnboardingNewRoute
  AdminOrganizationsOrgIdRoute: typeof AdminOrganizationsOrgIdRoute
  AdminPlansPlanIdRoute: typeof AdminPlansPlanIdRoute
  AdminPlansNewRoute: typeof AdminPlansNewRoute
  AdminAuditLogsIndexRoute: typeof AdminAuditLogsIndexRoute
  AdminBillingIndexRoute: typeof AdminBillingIndexRoute
  AdminFeatureFlagsIndexRoute: typeof AdminFeatureFlagsIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminOnboardingIndexRoute: typeof AdminOnboardingIndexRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminPlansIndexRoute: typeof AdminPlansIndexRoute
  AdminServerIndexRoute: typeof AdminServerIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSystemTemplatesIndexRoute: typeof AdminSystemTemplatesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBillingSubscriptionIdRoute: AdminBillingSubscriptionIdRoute,
  AdminBillingDashboardRoute: AdminBillingDashboardRoute,
  AdminOnboardingTaskIdRoute: AdminOnboardingTaskIdRoute,
  AdminOnboardingNewRoute: AdminOnboardingNewRoute,
  AdminOrganizationsOrgIdRoute: AdminOrganizationsOrgIdRoute,
  AdminPlansPlanIdRoute: AdminPlansPlanIdRoute,
  AdminPlansNewRoute: AdminPlansNewRoute,
  AdminAuditLogsIndexRoute: AdminAuditLogsIndexRoute,
  AdminBillingIndexRoute: AdminBillingIndexRoute,
  AdminFeatureFlagsIndexRoute: AdminFeatureFlagsIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminOnboardingIndexRoute: AdminOnboardingIndexRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminPlansIndexRoute: AdminPlansIndexRoute,
  AdminServerIndexRoute: AdminServerIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSystemTemplatesIndexRoute: AdminSystemTemplatesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CreateOrgRoute: CreateOrgRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
